---
title: Parameters in functies
hero_image: images/banner.png
description: parameterbeschrijving
version: 4
listed: false
copyedit: false
last_tested: "2021-10-27"
steps:
  - title: Parameters in functies
